kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: qbittorrent
  namespace: filme
  annotations:
    ingress.kubernetes.io/auth-type: "forward"
    ingress.kubernetes.io/auth-url: "https://auth.stoicatedy.ovh/api/verify?rd=https://auth.stoicatedy.ovh"
spec:
  rules:
    - host: qbittorrent.stoicatedy.ovh
      http:
        paths:
          - path: /
            backend:
              serviceName: qbittorrent
              servicePort: 8080
