apiVersion: v1
kind: ConfigMap
metadata:
  name: email-postfix
data:
  main.cf: |
    # POSTFIX config file, adapted for SimpleLogin
    smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
    biff = no

    debug_peer_level = 4
    smtp_host_lookup = native
    lmtp_host_lookup = native
    ignore_mx_lookup_error = yes
    disable_dns_lookups = yes

    # appending .domain is the MUA's job.
    append_dot_mydomain = no

    # Uncomment the next line to generate "delayed mail" warnings
    #delay_warning_time = 4h

    readme_directory = no

    # See http://www.postfix.org/COMPATIBILITY_README.html -- default to 2 on
    # fresh installs.
    compatibility_level = 2

    # TLS parameters
    smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
    smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    smtpd_use_tls=yes
    smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
    smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache

    # See /usr/share/doc/postfix/TLS_README.gz in the postfix-doc package for
    # information on enabling SSL in the smtp client.

    alias_maps = hash:/etc/aliases
    mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 10.0.0.0/8

    # Set your domain here
    myhostname = mail.stoicatedy.ovh
    mydomain = stoicatedy.ovh
    myorigin = stoicatedy.ovh

    relay_domains = pgsql:/etc/postfix/pgsql-relay-domains.cf
    transport_maps = pgsql:/etc/postfix/pgsql-transport-maps.cf

    # HELO restrictions
    smtpd_delay_reject = yes
    smtpd_helo_required = yes
    smtpd_helo_restrictions =
        permit_mynetworks,
        reject_non_fqdn_helo_hostname,
        reject_invalid_helo_hostname,
        permit

    # Sender restrictions:
    smtpd_sender_restrictions =
        permit_mynetworks,
        reject_non_fqdn_sender,
        reject_unknown_sender_domain,
        permit

    # Recipient restrictions:
    smtpd_recipient_restrictions =
      reject_unauth_pipelining,
      reject_non_fqdn_recipient,
      reject_unknown_recipient_domain,
      permit_mynetworks,
      reject_unauth_destination,
      reject_rbl_client zen.spamhaus.org,
      reject_rbl_client bl.spamcop.net,
      permit
  pgsql-relay-domains.cf: |
    # postgres config
    hosts = 10.43.56.116
    user = myuser
    password = mypassword
    dbname = simplelogin

    query = SELECT domain FROM custom_domain WHERE domain='%s' AND verified=true 
        UNION SELECT '%s' WHERE '%s' = 'stoicatedy.ovh' LIMIT 1;
  pgsql-transport-maps.cf: |
    # postgres config
    hosts = 10.43.56.116
    user = myuser
    password = mypassword
    dbname = simplelogin

    # forward to smtp:email-emailhandler:20381 for custom domain AND email domain
    query = SELECT 'smtp:email-emailhandler:20381' FROM custom_domain WHERE domain = '%s' AND verified=true 
        UNION SELECT 'smtp:email-emailhandler:20381' WHERE '%s' = 'stoicatedy.ovh' LIMIT 1;