kind: Deployment
apiVersion: apps/v1
metadata:
  name: bitwarden
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: bitwarden
  template:
    metadata:
      labels:
        k8s-app: bitwarden
    spec:
      containers:
        - name: bitwarden
          image: bitwardenrs/server:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            limits:
              memory: "100Mi"
              cpu: "500m"

      nodeSelector:
        "beta.kubernetes.io/os": linux
