version: "3"

services:
  traefik:
    image: traefik:latest
    userns_mode: "host"
    command: >
      --docker
      --logLevel=INFO
      --insecureskipverify
      --defaultentrypoints=http,https
      --entryPoints=Name:https\ Address::443\ TLS
      --entryPoints=Name:http\ Address::80\ Redirect.EntryPoint:https
      --acme
      --acme.storage=/acme.json
      --acme.entryPoint=https
      --acme.email=stoicatedy@gmail.com
      --acme.domains='*.stoicatedy.ovh'
      --acme.domains='stoicatedy.ovh'
      --acme.dnsChallenge.provider=cloudflare
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./acme.json:/acme.json
    container_name: traefik
    networks:
      - default
    env_file: ./env.txt
    restart: always

networks:
  default:
    external:
      name: web
