apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: router
  namespace: tedy
spec:
  schedule: "0 */1 * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: router
              image: tedyst/cronrunner:v1.1
              lifecycle:
                postStart:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - cp /key/key /app/key
              env:
                - name: TARGET
                  value: "192.168.1.1"
                - name: USER
                  value: "admin"
                - name: COMMAND
                  value: "/jffs/.asusrouter"
              volumeMounts:
                - mountPath: /key
                  name: key
          volumes:
            - name: key
              secret:
                secretName: router
          restartPolicy: OnFailure
