kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: ombi
  namespace: filme
spec:
  rules:
    - host: ombi.stoicatedy.ovh
      http:
        paths:
          - path: /
            backend:
              serviceName: ombi
              servicePort: 3579
