apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  url: https://argo.stoicatedy.ovh

  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: 45463b75c4193f120fb6
          clientSecret: 821f59c24cd75fd0871c24bcf232bf428af99064
          orgs:
          - name: tedystorg
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow

    g, tedystorg, role:org-admin