apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: authelia
data:
  config.yml: |-
    port: 10001
    logs_level: debug
    jwt_secret: some_secret
    default_redirection_url: https://stoicatedy.ovh
    authentication_backend:
      file:
        path: /secret/users_database.yml
    access_control:
      default_policy: deny
      rules:
        - domain: "*.stoicatedy.ovh"
          policy: two_factor
    session:
      secret: some_secret
      expiration: 3600000
      inactivity: 300000
      domain: stoicatedy.ovh
    regulation:
      max_retries: 3
      find_time: 120
      ban_time: 300
    storage:
      local: 
        path: /storage/store
    notifier:
      filesystem:
        filename: /dev/stdout
