apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
spec:
  template:
    spec:
      containers:
      - name: kube-hunter
        image: aquasec/kube-hunter 
        command: ["python", "kube-hunter.py"]
        args: ["--pod"]
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      restartPolicy: Never
  backoffLimit: 4
