apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp
  namespace: tedy
  labels:
    app: ftp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      labels:
        app: ftp
    spec:
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      containers:
        - name: ftp
          resources:
            limits:
              cpu: "2000m"
              memory: "300M"
            requests:
              cpu: "200m"
              memory: "300M"
          image: tedyst/docker-ftp-server:latest
          ports:
            - containerPort: 20
              hostPort: 20
            - containerPort: 21
              hostPort: 21
          volumeMounts:
            - mountPath: /media
              name: media
      volumes:
        - name: media
          hostPath:
            path: /var/lib/rancher/NFS
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: arm
        kubernetes.io/hostname: tedy-raspberry