apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-db
data:
  force.cnf: |
    [mysqld]
    slow_query_log = 1
    slow_query_log_file = /etc/stdout
    long_query_time=1
  docker.cnf: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
  mysqld_safe_syslog.cnf: |
    [mysqld_safe]
    skip_log_error
    syslog