apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: tedy
  labels:
    app: jellyfin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      containers:
        - name: jellyfin
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: "10000m"
              memory: "300M"
            requests:
              cpu: "500m"
              memory: "300M"
          image: linuxserver/jellyfin:20200216-ls13
          ports:
            - containerPort: 8096
              protocol: TCP
            - containerPort: 1900
              hostPort: 1900
              protocol: UDP
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: media-volume
              mountPath: /media
            - name: videocard
              mountPath: /dev/dri
          securityContext:
            privileged: true
      volumes:
        - name: config-volume
          hostPath:
            path: /media/hddext4/jellyfin/config
        - name: media-volume
          hostPath:
            path: /media/hddext4/jellyfin/media
        - name: videocard
          hostPath:
            path: /dev/dri
