apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
    # metrics.prometheus.enabled: "true"
    kubernetes.ingressEndpoint.useDefaultPublishedService: "true"
    acme.enabled: "true"
    acme.challengeType: "dns-01"
    acme.dnsProvider.name: "cloudflare"
    acme.email: "stoicatedy@gmail.com"
    acme.domains.enabled: "true"
    acme.dnsProvider.existingSecretName: "traefik-cloudflare"
    acme.domains.domainsList[0].main: "*.stoicatedy.ovh"
    acme.staging: "false"
    debug.enabled: "false"
    serviceType: "ClusterIP"
    externalTrafficPolicy: ""
    deployment.hostPort.httpsEnabled: "true"
    deployment.hostPort.httpEnabled: "true"
    deployment.hostPort.httpsPort: "444"
    deployment.hostPort.httpPort: "81"

