kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8dash
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: k8dash
  template:
    metadata:
      labels:
        k8s-app: k8dash
    spec:
      containers:
        - name: k8dash
          image: tedyst/k8dash:latest
          ports:
            - containerPort: 4654
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 4654
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            limits:
              memory: "100Mi"
              cpu: "500m"

      nodeSelector:
        "beta.kubernetes.io/os": linux
